def displayMenu():
    print("                    ---------------------------------------------")
    print("                    -                                           -")
    print("                    -                                           -")
    print("                    -         Chuong trinh thong minh           -")
    print("                    -                                           -")
    print("                    -                                           -")
    print("                    ---------------------------------------------")
    print()
    print("                    ====================MENU====================")
    print()
    print("Xin vui lòng chọn: ")
    print("1. Xem lịch. ")
    print("2. Tính lương: ")
    print("3. Xem lương: ")
    print("4. Xem thông tin nhân viên: ")
    print("5. Tính điểm của học sinh: ")
    print("6. Thoát chương trình: ")
